version: '3.8'

services:
  svelte:
    image: svelte-app
    build:
      context: ./
    ports:
      - 5173:5173
    volumes:
      - ./svelte:/app
    command: bash -c "yarn install && yarn dev --host"