version: '3.8'

services:
  svelte:
    image: svelte-app
    build:
      context: ./
    ports:
      - 5173:5173
    volumes:
      - ./src:/app/src
      - ./static:/app/static
      - ./playwright.config.ts:/app/playwright.config.ts
      - ./svelte.config.js:/app/svelte.config.js
      - ./tsconfig.json:/app/tsconfig.json
      - ./vite.config.ts:/app/vite.config.ts
    command: bash -c "yarn install && yarn dev -- --host"